### ISSUE TITLE
suggest the extension can config jdk in javaconfig.json

### ISSUE THREAD

**Issue by chwentao** [georgewfraser/vscode-javac#10]
suggest the extension can config `jdk` in `javaconfig.json` file,

**Comment by chwentao** [comment]
why？？？？？？？！！！！！！！！！

**Comment by georgewfraser** [comment]
The implementation uses Java 8 libraries and tons of Java 8 syntax, it's not possible to run it on Java 7. javaconfig.json has nothing to do with it

**Comment by chwentao** [comment]
Hello, I mean a lot of time will be installed on multiple computers jdk versions, you can specify a specific configuration to provide a version of this plug-in used; current development java project with jdk8 not many, so you can make the project a little flexible.
