### ISSUE TITLE
Classpath Issues on Windows

### ISSUE THREAD

**Issue by ecmel** [georgewfraser/vscode-javac#11]
Hi,

I generated classpath.txt by Maven but still getting undefined symbols for a Spring Boot project, on Windows. (Path separator ";" File separator "\") 

Everything works for jdk and project local classes.

Demo Spring Boot Project:
[demo.zip](https://github.com/georgewfraser/vscode-javac/files/300317/demo.zip)

**Comment by ecmel** [comment]
Workaround:

Seems to be the absolute paths.

İf I use relative paths it works:

<localRepoProperty>../../.m2/repository</localRepoProperty>

**Comment by ganeshvelanki** [comment]
thanks man.. your demo project is good..

and Ctrl + space is not showing up! Untill I type a char, nothing shows up.

**Comment by georgewfraser** [comment]
Should be fixed by https://github.com/georgewfraser/vscode-javac/commit/4e818e3a7065dce9e7459e8571cc7079823f47e7
