### ISSUE TITLE
How to make it work with simple android project?

### ISSUE THREAD

**Issue by airstep** [georgewfraser/vscode-javac#12]
And how to generate classpath.txt file by gradle?
And what folders to include?

**Comment by jpierson** [comment]
I'm also working with Graddle for a non-android project and I'm by no means a Java tooling expert. Not sure how or whether this extension will work for my type of project.

**Comment by vitalyster** [comment]
Works for me as following - added this to `build.gradle`:
```
def classpathTxt = new File("classpath.txt")
classpathTxt.withWriter { w ->
    w << sourceSets.main.compileClasspath.asPath
}
```

**Comment by airstep** [comment]
Error:
> Could not find property 'compileClasspath' on source set main.

**Comment by vitalyster** [comment]
@airstep my example was for non-android project, see http://stackoverflow.com/a/28224687/1097384 for explanation of android project structure, you may need `debug.javaCompile.classpath.asPath` or something

**Comment by airstep** [comment]
Trying like this:

    android.applicationVariants.each { variant ->
        variant.javaCompile.classpath += configurations.provided
    }

    def classpathTxt = new File("classpath.txt")
    classpathTxt.withWriter { w ->
        w << debug.javaCompile.classpath
    }

Error is: Could not find property 'debug'

**Comment by andersonlucasg3** [comment]
I made it work for most of my Android java code with this gradle snippet

android.libraryVariants.all { variant ->
    def rootDir = project.rootDir
    def localProperties = new File(rootDir, "local.properties")
    if (localProperties.exists()) {
        Properties properties = new Properties()
        localProperties.withInputStream { instr ->
            properties.load(instr)
        }
        def sdkDir = properties.getProperty('sdk.dir')
        def androidJarPath = sdkDir + "/platforms/" + android.compileSdkVersion + "/android.jar"

        def file = new File("classpath.txt");
        file.delete();
        file.text = variant.javaCompile.classpath.asPath + ":" + androidJarPath;
    }
}

But it still need lots of improvements.
Once in a time the language support crashes and stops providing the auto completion.
Hope it helps.

**Comment by gulshan** [comment]
Can someone post a generated classpath.txt file please? I think that will help.

**Comment by georgewfraser** [comment]
Closed by https://github.com/georgewfraser/vscode-javac/pull/20
