### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by felixfbecker** [georgewfraser/vscode-javac#13]
I have a repository that contains several projects in subdirectories. I added a javaconfig.json for each which looks like this:
```json
{
  "sourcePath": ["src"],
  "classPathFile": "classpath.txt",
  "outputDirectory": "bin"
}
```
Since the project is not using Maven I added the classpath.txt manually with this content:
```
C:\Users\felix\.p2\pool\plugins\org.junit_4.12.0.v201504281640\junit.jar
```
(it would be easier if I could specify this right in javaconfig.json or if you also looked at the environment variable CLASSPATH)

No matter in which file I go, I do not get rich IntelliSense and goto symbol yields "We have no symbol information for this file".

**Comment by georgewfraser** [comment]
Should be fixed by https://github.com/georgewfraser/vscode-javac/commit/4e818e3a7065dce9e7459e8571cc7079823f47e7
