### ISSUE TITLE
Duplicate Class Errors

### ISSUE THREAD

**Issue by ecmel** [georgewfraser/vscode-javac#14]
Hi,

I am getting duplicate class errors for some of my classes, (named UserGroup and User) although they are unique within the namespace and compiles cleanly.

**Comment by laszlofarkas** [comment]
I tried out with an "installed" maven project. - So the "target" folder contains the compiled code. - And I got the same error. But after I changed the "outputDirectory" in javaconfig.json file, then the problem disappear.
So my guess is that the plugin found the same class twice: once in source folder and once in the output folder.

**Comment by ecmel** [comment]
Tried that but after I exit and reopen the project the same thing happens.

**Comment by alvaromunoz** [comment]
I had to empty it:

```
{
    "sourcePath": ["test", "src"],
    "outputDirectory": "",
    "classPathFile": "classpath.txt"
}
```

**Comment by georgewfraser** [comment]
I believe this is definitively resolved now that the plugin only uses the public-facing java compiler API and caches fewer things between compiles.
