### ISSUE TITLE
Use "@" for find symbol instead of "#"

### ISSUE THREAD

**Issue by navneetkarnani** [georgewfraser/vscode-javac#15]
When I type Cmd+Shift+O, the find symbol interaction launches. This shows the "@" symbol at the beginning and then shows a message saying "Unfortunately we have no symbol information for the file". But, when typing "#", the message "type to search for symbols" is shown.

**Comment by georgewfraser** [comment]
Fixed by https://github.com/georgewfraser/vscode-javac/commit/9e4545932ca2e4173da7e8c8061856b1b4d26f26
