### ISSUE TITLE
Errors on key press and autocomplete doesn't work

### ISSUE THREAD

**Issue by davidnussio** [georgewfraser/vscode-javac#16]
OS: Linux Ubuntu (16.04)

Visual Studio Code
Version 1.3.0
Commit e724f269ded347b49fcf1657fc576399354e6703
Date 2016-07-07T16:50:12.291Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

![selection_042](https://cloud.githubusercontent.com/assets/324371/16690315/92a55442-4527-11e6-8310-72a2875a446d.png)

**Comment by georgewfraser** [comment]
It's a lot more reliable now, these kinds of things should no longer happen.
