### ISSUE TITLE
Is there any way to config JAVA_HOME?

### ISSUE THREAD

**Issue by mtunique** [georgewfraser/vscode-javac#17]
I don't want to config Java8 as the default.

**Comment by ianrobrien** [comment]
It looks like waterfall logic to first pull from JAVA_HOME and then PATH, but otherwise there is no other way to set this value. It would be nice to pull it the path from VS Code config setting.

**Comment by georgewfraser** [comment]
You can now set java.home using vs code settings https://github.com/georgewfraser/vscode-javac#optional-settings
