### ISSUE TITLE
Unable to build the maven project as there are compile error

### ISSUE THREAD

**Issue by jcgarciam** [georgewfraser/vscode-javac#27]
Class **LanguageDescriptionImpl** is missing, did you have to compile a dependency manually to get it to work?

> [INFO] ------------------------------------------------------------------------                                             
> [INFO] BUILD FAILURE                                                                                                        
> [INFO] ------------------------------------------------------------------------                                             
> [INFO] Total time: 2.072 s                                                                                                  
> [INFO] Finished at: 2016-09-15T00:04:06+02:00                                                                               
> [INFO] Final Memory: 18M/284M                                                                                               
> [INFO] ------------------------------------------------------------------------                                             
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project javac
> -services: Compilation failure: Compilation failure:                                                                        
> [ERROR] /home/forzaken/dev/projects/vscode-javac/src/main/java/org/javacs/JavaLanguageServer.java:[83,9] cannot find symbol 
> [ERROR] symbol:   class LanguageDescriptionImpl                                                                             
> [ERROR] location: class org.javacs.JavaLanguageServer                                                                       
> [ERROR] /home/forzaken/dev/projects/vscode-javac/src/main/java/org/javacs/JavaLanguageServer.java:[83,44] cannot find symbol
> [ERROR] symbol:   class LanguageDescriptionImpl                                                                             
> [ERROR] location: class org.javacs.JavaLanguageServer                                                                       
> [ERROR] -> [Help 1]

**Comment by georgewfraser** [comment]
Fixed by https://github.com/georgewfraser/vscode-javac/pull/26
