### ISSUE TITLE
vscode-javac could benefit from VS Code's language service protocol

### ISSUE THREAD

**Issue by dbaeumer** [georgewfraser/vscode-javac#3]
@georgewfraser I stumble over your plugin in the market place and it is quite cool. I looked at the source code to understand how you provided the Java smartness. Nice idea to reuse tools.jar from the JDK.

I noticed that you came up with our own JSON protocol to talk to your Java process. I would like to point you to two GitHub repositories we maintain to ease such integration:

https://github.com/Microsoft/vscode-languageserver-protocol
https://github.com/Microsoft/vscode-languageserver-node

The first one is basically a JSON-RPC protocol specification that can be implemented by language servers in the programming language of their choice. The second one provides client and server implementations in node. Even if your server is implemented in a language different than node you could still profit from implementing the protocol since you get the client for free. The npm vscode-languageclient module basically wires up the protocol to VSCode's API based on capabilities returned from the server.

The following issue list implementers of the protocol in different languages:  https://github.com/Microsoft/vscode-languageserver-protocol/issues/8

If you want to look for a simple example on how that works in action you can have a look at https://github.com/Microsoft/vscode-languageserver-node-example. Please note that the client in this example starts the server as a node process. However the client library supports starting any kind of server as well.

Some background about me: I am a developer in VS Code responsible for language service integration.

If you are interested in making use of the protocol and the client library I am happy to answer questions and to help.

**Comment by dbaeumer** [comment]
As you can see in Microsoft/vscode-languageserver-protocol#8 @svenefftinge is working on a Java implementation of the protocol as well. May be it would make sense to join forces here.

**Comment by dbaeumer** [comment]
We also started to write a wiki of users and implementers: https://github.com/Microsoft/vscode-languageserver-protocol/wiki/Protocol-Implementations

**Comment by georgewfraser** [comment]
This makes a lot of sense. The javac parse tree contains a ton of useful information, this will make it much easier to incrementally add support for VS code features. I'll refactor to use this protocol but may not get started until next weekend.

**Comment by svenefftinge** [comment]
Just to be clear. We are not working on a Java language server like you, but have implemented the protocol in Java to be used by any services implemented in Java. That implementation of the protocol is here (https://github.com/TypeFox/ls-api/tree/master/io.typefox.lsapi/src/main/java/io/typefox/lsapi) and you can even already grab it from sonatype's SNAPSHOT repo.

It makes sense to use the same java types, since we will be able to skip the JSON serialization when talking between a Java client (e.g. Eclipse Che) and a Java based language server.

**Comment by svenefftinge** [comment]
Btw. are you aware of JDT from Eclipse? AFAIK it is a bit better suited for a java implementation as it already knows a lot about e.g. code completion. Big parts run nicely without Eclipse.
Just wanted to make sure you haven't missed it.

**Comment by georgewfraser** [comment]
Thanks @svenefftinge I will try to use your implementation. Can you point me to a "hello world" example of how to wire up a language server written in Java that leverages this infrastructure?

I originally tried to set this up using JDT, but I found it to be very intertwined with the internals of eclipse. javac produces a great parse tree, once you have that it isn't that hard to get autocomplete etc.

**Comment by georgewfraser** [comment]
@svenefftinge Never mind I found good examples of usage in the tests. But the sonatype snapshot appears to be out of date, it's missing some really basic stuff. Can you please update?

**Comment by dbaeumer** [comment]
Great. If you need any support please let me know.

**Comment by svenefftinge** [comment]
@georgewfraser the SNAPSHOT built got updated this morning.

**Comment by georgewfraser** [comment]
Ok I switched to the language service protocol for v0.0.7. It eliminates basically all the client side code! It's going to be much easier to build out the rest of the vscode features. Thanks for the fantastic suggestion @dbaeumer

@svenefftinge your implementation of the protocol was very helpful in getting this done fast.

**Comment by dbaeumer** [comment]
This is awesome. Thanks for using the protocol. Any objection to list you as an implementer here: https://github.com/Microsoft/vscode-languageserver-protocol/wiki/Protocol-Implementations

**Comment by georgewfraser** [comment]
No problem go ahead.

**Comment by dbaeumer** [comment]
Thanks.
