### ISSUE TITLE
Couldn't start client Language support for Java

### ISSUE THREAD

**Issue by mutantkeyboard** [georgewfraser/vscode-javac#38]
I'm using a macOS Sierra, and JDK 8u101 (I don't bother with updating it so often).
As you can see on my Terminal I'm using `JDK_PATH`, and `javac` path is correctly set. 
![screen shot 2016-11-02 at 16 06 33 2](https://cloud.githubusercontent.com/assets/1167494/19934412/d685b1ac-a116-11e6-8cb3-82a76dd932ba.png)
Yet I still get an error `Couldn't start client Language support for Java`. 
Does it really require a newest version of JDK?

**Comment by rmaclean** [comment]
Same issue and I have 1.8.0_111 on El Capitan

**Comment by twq1108** [comment]
I suggest that maybe you should try to use JAVA_HOME or JDK_HOME instead of JDK_PATH according to the instructions given by the extension "Language support for Java ™ for Visual Studio Code".

**Comment by mutantkeyboard** [comment]
As @twq1108 has suggested a quick fix for this is adding an: 
`export JAVA_HOME=`/usr/libexec/java_home` ` to your _rc_ file. It can be .bashrc, .zshrc, .bash_profile, or anything else you use. 
Then just issue a command `source ~/.zshrcz` (in my case - replace .zshrc with your corresponding file). 
Enjoy
