### ISSUE TITLE
source set-specific javaconfig.json

### ISSUE THREAD

**Issue by ags799** [georgewfraser/vscode-javac#39]
Thanks for posting the gradle task for generating a `javaconfig.json`. One shortcoming is that it only grabs `compile` dependencies, and skips over other dependency groups, like `testCompile`.

It's straightforward to add in these other dependency groups to the generated `classpath.txt`. But as an extension, is it possible to make these classpaths source-set specific?

That is, if I have the following build.gradle:
```groovy
dependencies {
    compile 'com.google.guava:guava:20.0'
    compile 'junit:junit:4.12'
}
```
and two source sets, `src/main/java` & `src/test/java`, can we have some set of `javaconfig.jsons` specify different classpaths for these source sets? That is, it would have the guava jar on the `main` set's classpath and the guava *and* junit jars on the `test` set's classpath.

**Comment by georgewfraser** [comment]
javaconfig.json has been eliminated in favor of automatic inference + [.vscode/settings.json](https://github.com/georgewfraser/vscode-javac#settings)
