### ISSUE TITLE
Auto Import  class

### ISSUE THREAD

**Issue by eHattori** [georgewfraser/vscode-javac#44]
Hello =) 

The plugin has some plan for do auto import equal the autoimport to typescript?

https://marketplace.visualstudio.com/items?itemName=steoates.autoimport

**Comment by georgewfraser** [comment]
This is implemented in the latest version

**Comment by albfan** [comment]
Not sure how this is triggered in a ls client. Any tip?

**Comment by georgewfraser** [comment]
It's part of auto-format. If there are any unresolved symbols that look like classes, JLS looks for classes with that name and auto-imports them. Occasionally there are ambiguities but it works pretty well.

**Comment by albfan** [comment]
I tried the simplest class with main and "hello world", then add a Vector var, but didn't receive any ls action to add those imports, am I missing something?

**Comment by georgewfraser** [comment]
The auto-add-imports code tries to add imports when you save: https://github.com/georgewfraser/java-language-server/blob/65ca5e4e77e31edddefc1bb78e476912cf7c2ea3/src/main/java/org/javacs/CompileBatch.java#L291

It doesn't *always* work. Code-actions to add imports would be a nice addition. Also, it would be nice if autocomplete added imports automatically.
