### ISSUE TITLE
Allow for arbitrary jars in settings.json

### ISSUE THREAD

**Issue by abarisain** [georgewfraser/vscode-javac#54]
I've come across this extension in my long quest to replace Android Studio with a more lightweight solution.  

None of the various Java plugins on Atom/Vim/VSCode worked well for my project, with every autodetection feature collapsing on itself.
Except for this extension, which magically picks up almost everything correctly.

This brings me to an issue with the settings.json only configuration: there is no way to define JARs as external dependencies: For my project to work correctly, I need to reference android.jar. I have no problem hardcoding the Android Jar version in a workspace settings.json, as it doesn't change often. 

Unfortunately, the android sdk does not come as a maven/gradle artifact, so I can't use that syntax.
Ideally, I'd like to add "java.externalDependencies": ["${ANDROID_HOME}/platforms/android-26/android.jar"] to my settings.json, and commit that in the workspace for everybody to use.
(Env var support would be nice, but I could live without it)

Is there something I'm missing?  

Thanks for the great work on this extension. It works much better for my use case than redhat's.

**Comment by georgewfraser** [comment]
Fixed by 793139af71d0a8fd203e3557fd45f4258153729f

**Comment by abarisain** [comment]
Amazing. Thanks!
