### ISSUE TITLE
Upgrade to ls-api 0.2.0-SNAPSHOT

### ISSUE THREAD

**Issue by svenefftinge** [georgewfraser/vscode-javac#6]
We had to change the signatures of the service methods to return a CompletableFuture because at first we misunderstood how synchronization should be handled in the protocol. See https://github.com/TypeFox/ls-api/issues/5 for more details.

We bumped the version so you don't get broken immediately, but you should upgrade if you can. We will publish the SNAPSHOT tomorrow morning (Europe).

**Comment by svenefftinge** [comment]
Please wait with merge, as the 0.2.0 SNAPSHOTS are not yet published to sonatype snapshots. Will add a comment once they are.

**Comment by georgewfraser** [comment]
OK the changes don't look too bad, I should be able to just return CompletableFuture.completedFuture(...) everywhere, right?

**Comment by svenefftinge** [comment]
Cool! The snapshot is now deployed.

**Comment by georgewfraser** [comment]
I have upgraded but there are still fundamental problems with reading large messages: https://github.com/TypeFox/ls-api/issues/6
