### ISSUE TITLE
How the AST is built from the incomplete source and Identify the statements

### ISSUE THREAD

**Issue by nadeeshaan** [georgewfraser/vscode-javac#66]
I would like to get high-level implementation details about how the LS implementation identifies the statements and build the AST from the incomplete source. Does this implementation depend on the Grammar and the Parser or otherwise?

**Comment by georgewfraser** [comment]
This language server uses the [programmatic API](https://docs.oracle.com/javase/10/docs/api/jdk.compiler-summary.html) to the official JDK java compiler. The parsing and typechecking is exactly the same implementation that javac uses; the JDK provides a nice api to inspect the typechecked tree.

The java compiler allows you to compile one file at a time, so it's somewhat incremental. When compiling a file for a local operation, like autocomplete, we speed up compilation by erasing the bodies of all methods that don't contain the cursor. This is sufficient to compile a file in < 100 ms, even very large files.
