### ISSUE TITLE
consider doing this via ENSIME?

### ISSUE THREAD

**Issue by fommil** [georgewfraser/vscode-javac#9]
Hi, it looks like we duplicating a lot of efforts. Would you consider providing language server support under https://github.com/ensime/ensime-server ?

**Comment by georgewfraser** [comment]
I'm not sure what that would mean. I looked at ensime a while ago and it seemed java support was not a priority.

**Comment by fommil** [comment]
We have Java support for quite a few things and the indexing/searching is all shared with the Scala support. We even have a Google summer of code student working on that.

The idea would be that by working together we'd benefit from each other's work. Ensime has a pretty big userbase and many contributors. You could make a difference on the Java support side while benefiting from search and other existing infrastructure (such as automated releases).

If you're uncomfortable with Scala, you could write the core java support in Java, or even publish in a separate jar.

**Comment by georgewfraser** [comment]
Thanks for taking the time to tell me about ensime @fommil. I don't think it would be worthwhile to merge this with ensime; the differences in our approaches and goals are just too great.

**Comment by fommil** [comment]
Oh that's a shame
